### ISSUE TITLE
Any chance to make this work on LuaJIT/Lua5.1?

### ISSUE THREAD

**Issue by EvaisaDev** [cryi/hjson-lua#1]
I was hoping to use this in LuaJIT but it appears to error out when trying to encode a table.
Same with decoding, the error i am getting is `["lib/hjson/decoder.lua"]:157: malformed pattern (missing ']')`

**Comment by asumbek** [comment]
`\0` escape sequence is causing the problem. In older Lua versions before 5.3, `\0` isn't sanitized correctly and act as an end of a string, so Lua throws an error about incomplete pattern.

**Comment by cryi** [comment]
Hello @EvaisaDev,

I apologize for not noticing this issue earlier.

I've now modified the code to ensure compatibility with both Lua 5.1 and 5.2. However, during this process, I noticed that the Unicode support in these versions is quite limited. Consequently, I'm not entirely sure how well these adjustments will work for your specific needs. Please give it a try and let me know if you encounter any problems.

**Comment by cryi** [comment]
Hi @EvaisaDev, I am closing this issue now due to inactivity. If you require further assistance, please feel free to create a new issue.
